# Generated by Django 4.0.4 on 2022-05-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('PackageId', models.AutoField(primary_key=True, serialize=False)),
                ('PackageName', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('Admin', models.BooleanField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('RecipeId', models.AutoField(primary_key=True, serialize=False)),
                ('RecipeName', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('VotesQuantity', models.FloatField()),
                ('AverageOpinion', models.FloatField()),
                ('Description', models.CharField(max_length=300)),
                ('Ingredients', models.CharField(max_length=300)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeHealthyApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeHealthyApp.users')),
            ],
        ),
    ]
