# Generated by Django 4.0.4 on 2022-05-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeHealthyApp', '0002_users_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
