# Generated by Django 4.0.4 on 2022-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeHealthyApp', '0003_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Content',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
