# Generated by Django 4.0.4 on 2022-05-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeHealthyApp', '0004_feedback_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Ingredients',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='PhotoFileName',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='RecipeName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='PhotoFileName',
            field=models.CharField(max_length=400),
        ),
    ]
